/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_unisound_UniVprJni */

#ifndef _Included_cn_unisound_UniVprJni
#define _Included_cn_unisound_UniVprJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_unisound_UniVprJni
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_unisound_UniVprJni_create__(JNIEnv *, jobject);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    create
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jlong JNICALL Java_cn_unisound_UniVprJni_create__Ljava_lang_String_2I(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    setOptionInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_setOptionInt(JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    setOptionString
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_setOptionString(JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_start(JNIEnv *, jobject, jlong);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    login
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_login(JNIEnv *, jobject, jlong);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_stop(JNIEnv *, jobject, jlong);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    getResult
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_unisound_UniVprJni_getResult(JNIEnv *, jobject, jlong);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_release(JNIEnv *, jobject, jlong);

/*
 * Class:     cn_unisound_UniVprJni
 * Method:    feedBuffer
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_cn_unisound_UniVprJni_feedBuffer(JNIEnv *, jobject, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
