#ifndef _USC_SET_OPTION_KEY_H_
#define _USC_SET_OPTION_KEY_H_

#define AUDIO_ENC_METH_OPUS		"opus"
#define AUDIO_ENC_METH_OPUS_NB	"opus-nb"
#define AUDIO_ENC_METH_SPEEX	"speex"
#define ASR_OPT_RSP_ENTITY  "req_audio_url"

#define AUDIO_FORMAT_PCM_16_TO_8K "pcm16to8k"
#define AUDIO_FORMAT_AMRNB_TO_16K "amrnbto16k"
#define AUDIO_FORMAT_SPEEX_16K       "speex16k"
#define AUDIO_FORMAT_SPEEX_OGG_16K   "speexogg16k"
#define AUDIO_FORMAT_SPEEX_8K        "speex8k"

#define AUDIO_FORMAT_USC_SPEEX_16K "uscspeex16k"
#define AUDIO_FORMAT_USC_OPUS_16K "uscopus16k"

#define AUDIO_FORMAT_PCM_NO_ENCODE_16k "pcm16knoen"
#define AUDIO_FORMAT_PCM_NO_ENCODE_8k "pcm8knoen"

#define AUDIO_FORMAT_MP3 "mp3"
#define AUDIO_FORMAT_PCM "pcm"

#define AUDIO_FORMAT_USC_SPEEX_8K "uscspeex8k"
#define AUDIO_FORMAT_USC_OPUS_8K "uscopus8k"

// get option key
enum {
	USC_GET_SESSION_ID = 21,
	USC_GET_UDID = 22,
	USC_GET_SESSION_ID_2 = 26,
	USC_GET_TMP_RESULT_PARAMETER = 34,
	USC_GET_LAST_RESULT = 51,
	USC_GET_TTS_LAST_RESULT = 52,
	USC_GET_TTS_LAST_RESULT_LEN = 53,
	USC_GET_ERROR_LOG = 54,
	USC_GET_TOKEN = 206,
};

// set option key
enum {
	ASR_VAD_ENABLED = 0,  // 0 OR 1, default value 0 (disable)
	ASR_VAD_TIMEOUT_ID = 1,  // (this value only valid when vad is enabled) from 500 to 10000, default value 3000 (means 3000ms)
	ASR_MAX_SPEECH_TIMEOUT_ID = 2,  // from 10 to 600, default value 60  (means 60s)
	ASR_PARTIAL_RESULT_ENABLED = 3,   // 0 means always wait, default value 20 (means 20s)
	ASR_WAITING_RESULT_TIMEOUT_ID = 4,   // 0 means always wait, default value 30 (means 30)
	//ASR_RESULT_FORMAT_ID = 5,   // default value 0 ( 0 means "text", 1 means "json")
	ASR_PCM_COMPRESS_ID = 6,   // from 0 to 10, default value 8
	ASR_DISABLE_PARTIAL_RESULT_ID = 7,
	OPT_IMEI_ID = 8,
	OPT_APP_KEY = 9,
	OPT_PACKAGE_NAME = 10,
	OPT_DEVICE_OS = 11,
	OPT_CARRIER = 12,
	OPT_NETWORK_TYPE = 13,
	OPT_USER_ID = 14,
	OPT_COLLECTED_INFO = 15,
	ASR_AUDIO_ENCODE_MTD = 16,
	ASR_MODLE_TYPE = 18,
	ASR_AUDIO_ENCODE_MTD8K = 19,
	OPT_UDID_ID = 22,
	ASR_ORAL_EVAL_TEXT = 23,
	ASR_OPT_USE_DECODE = 24,
	ASR_ORAL_TASK_TYPE = 26,
	ASR_ORAL_CONF_OP1 = 27,
	ASR_ORAL_CONF_OP2 = 28,
	ASR_REQ_SPEAKER_INFO = 32,
	ASR_SCENE_CONTEXTID = 31,
	OPT_ENGINE_PARAMETER = 34,
	ASR_RESULT_PARAMETER = 35,
	ASR_PUNCTUATION_ENABLE = 50,
	USC_OPT_ASR_ENCODE_BITRATE = 100,
	// 是否对数据编码并设置数据压缩比粗略估算，得到上传数据缓冲大小
	ASR_NET_PACKAGE_SIZE = 101,
	OPT_ENGINE_PARAMETER_2 = 104,
	ASR_RESULT_PARAMETER_2 = 105,  //

	OPT_REQUEST_TIMEOUT = 200,
	ASR_TRAFFIC_PARAMETER = 201,
	OPT_REQUEST_SLEEP_TIME = 202,
	OPT_USE_MD5 = 203,
	OPT_SECRET = 204,
	OPT_CRYPT_VERSION = 205,
	OPT_SET_TOKEN = 206,

	OPT_LOG_SWITCH = 208,
	OPT_LOG_WRITE = 209,
	OPT_LOG_FILE = 210,
	ASR_RESULT_FORMAT_ID = 1006,
	ASR_LANGUAGE_SELECT = 1007,

	SERVICE_STATUS_SELECT = 1015,
	OPT_LAST_SOCKET_ERROR = 1026,
	ASR_OPUS_BITRATE = 1027,
	USC_OPT_SET_CANCEL = 9998,

};

// out

enum {
	USC_ASR_APP_KEY_ = 9,
	USC_ASRUSER_ID = 14,
	USC_RECOGNITION_FIELD = 18,
	USC_LANGUAGE_SELECT = 20,
	USC_OPT_ENGINE_PARAMETER = 104,
	USC_NLU_PARAMETER = 201,
	USC_USER_SECRET = 204,
	USC_INPUT_AUDIO_FORMAT = 1001,
	USC_PUNCTUATION_ENABLED = 1002,
	USC_DECODE_FRAME_SIZE = 1003,
	USC_NOISE_FILTER = 1004,
	USC_RESULT_FORMAT = 1006,
	USC_SERVICE_STATUS_SELECT_ = 1015,
};

#endif