/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EncodeContent */

#ifndef _Included_EncodeContent
#define _Included_EncodeContent
#ifdef __cplusplus
extern "C" {
#endif

//JNIEXPORT jint JNICALL usc_CheckKeyValid (JNIEnv * env, jobject, jbyteArray key);

/*
 * Class:     EncodeContent
 * Method:    EncodeContent
 * Signature: ([B[B[B)I
 */
//JNIEXPORT jint JNICALL usc_EncodeContent(JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_casr_EncodeContent_EncodeTotalContent
    (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);
    
    
/*
 *
 * Class:     EncodeContent
 * Method:    DecodeTotalContent
 * Signature: ([B[B)I
 */
//JNIEXPORT jint JNICALL usc_DecodeTotalContent(JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_casr_EncodeContent_DecodeTotalContent
   (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray); 
    
/*
 * Class:     EncodeContent
 * Method:    DecodeContent
 * Signature: ([B[B[B)I
 */
//JNIEXPORT jint JNICALL usc_DecodeContent(JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
