/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

#ifndef _Included_TTS_JniUscClient_
#define _Included_TTS_JniUscClient_

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeCreate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeCreateExt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeCreateExt
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeRelease
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeSetOption
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeSetOption
  (JNIEnv *, jobject, jlong, jint, jstring);
	

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeStart
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeStart
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeStop
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeTextPut
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeTextPut
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeGetResult
 * Signature: (J[I[I[I)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeGetResult
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeGetOption
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeGetOption
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cn_yunzhisheng_tts_JniClient
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yunzhisheng_tts_JniClient_nativeGetVersion
  (JNIEnv *, jclass);

	
#ifdef __cplusplus
}
#endif
#endif
