/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_JniUscClient_
#define _Included_JniUscClient_

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     JniUscClient
 * Method:    create
 * Signature: (Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL usc_create
(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JniUscClient
 * Method:    setValue
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL usc_setOptionInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     JniUscClient
 * Method:    setValue
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL usc_setOptionString
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     JniUscClient
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL usc_start
(JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    login
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL usc_login
(JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL usc_stop
(JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    isactive
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL usc_isactive
  (JNIEnv *env, jobject, jlong, jbyteArray raw, jint len);

/*
 * Class:     JniUscClient
 * Method:    recognize
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL usc_recognize
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     JniUscClient
 * Method:    getResult
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL usc_getResult
(JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    getOptionValue
 * Signature: (JI)Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL usc_getOptionValue
(JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JniUscClient
 * Method:    cancel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL usc_cancel
(JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    destroy
 * Signature: (J)I
 */
JNIEXPORT void JNICALL usc_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JniUscClient
 * Method:    getLastErrno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL usc_getLastErrno
(JNIEnv *, jobject, jlong);
	
#ifdef __cplusplus
}
#endif
#endif
